<?php

namespace AppBundle\Repository;

/**
 * CrossTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrossTableRepository extends \Doctrine\ORM\EntityRepository
{
}
